# Generated by Django 4.0.3 on 2022-05-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_league'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
