# Generated by Django 4.0.3 on 2022-05-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_players_player_rename_teams_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesteam', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesname', models.CharField(max_length=300)),
                ('seriesteams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.seriesteam')),
            ],
        ),
    ]
