# Generated by Django 4.0.3 on 2022-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_seriesteam_seriesname'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsheading', models.CharField(max_length=300)),
                ('news', models.CharField(max_length=999999)),
            ],
        ),
    ]
