# Generated by Django 4.0.3 on 2022-06-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_leagueteams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueTeams',
            new_name='LeagueTeam',
        ),
        migrations.RenameField(
            model_name='leagueteam',
            old_name='leagueteams',
            new_name='leagueteam',
        ),
    ]
