# Generated by Django 4.0.3 on 2022-06-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_country_delete_leagueteam_alter_player_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesname',
            name='seriesteams',
        ),
        migrations.AddField(
            model_name='seriesname',
            name='seriesteams1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SeriesName', to='teams.country'),
        ),
        migrations.AddField(
            model_name='seriesname',
            name='seriesteams2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seriesteams2', to='teams.country'),
        ),
        migrations.DeleteModel(
            name='SeriesTeam',
        ),
    ]
