# Generated by Django 4.0.4 on 2022-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_news_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsheading', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='newsheading',
        ),
    ]
