# Generated by Django 4.0.4 on 2022-06-04 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 4, 15, 49, 8, 885228, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
