# Generated by Django 4.0.4 on 2022-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Img',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Dob'),
        ),
    ]
