# Generated by Django 4.0.4 on 2022-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_player_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='para',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='Para'),
        ),
    ]
