# Generated by Django 4.0.4 on 2022-06-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_alter_player_para'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Img',
            new_name='playerimg',
        ),
    ]
