# Generated by Django 4.0.4 on 2022-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_rename_img_player_playerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerimg',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
