# Generated by Django 4.0.3 on 2022-06-05 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_alter_events_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsheading',
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(default='', null=True, verbose_name='news'),
        ),
        migrations.AlterField(
            model_name='newsheading',
            name='newsheading',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.news'),
        ),
    ]
