# Generated by Django 4.0.3 on 2022-06-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_remove_news_newsheading_alter_news_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheading',
            name='news',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.news'),
        ),
        migrations.AlterField(
            model_name='newsheading',
            name='newsheading',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
