# Generated by Django 4.0.3 on 2022-06-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_remove_news_img_newsheading_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='events',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='events',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='seriesname',
            name='seriesteams1',
        ),
        migrations.RemoveField(
            model_name='seriesname',
            name='seriesteams2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leaguename',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='SeriesName',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
