# Generated by Django 4.0.3 on 2022-06-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_alter_playerinfo_options_alter_players_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.players'),
        ),
    ]
