# Generated by Django 4.0.3 on 2022-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_alter_teams_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='teaminfo',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='cen',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='cts',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='hcen',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='hs',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='mat',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='para',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='wick',
        ),
        migrations.AlterField(
            model_name='players',
            name='cen',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Cen'),
        ),
        migrations.AlterField(
            model_name='players',
            name='city',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='players',
            name='country',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='players',
            name='cts',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Cts'),
        ),
        migrations.AlterField(
            model_name='players',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Dob'),
        ),
        migrations.AlterField(
            model_name='players',
            name='hcen',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Hcen'),
        ),
        migrations.AlterField(
            model_name='players',
            name='hs',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Hs'),
        ),
        migrations.AlterField(
            model_name='players',
            name='mat',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Mat'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='players',
            name='para',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='players',
            name='runs',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='runs'),
        ),
        migrations.AlterField(
            model_name='players',
            name='wick',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Wick'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teaminfo',
            field=models.TextField(default='', null=True, verbose_name='teaminfo'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamname',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='teams'),
        ),
        migrations.DeleteModel(
            name='Playerinfo',
        ),
    ]
