# Generated by Django 4.0.3 on 2022-06-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0034_remove_players_teaminfo_remove_teams_cen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsheading1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='teams.newsheading'),
        ),
    ]
