# Generated by Django 4.0.3 on 2022-06-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0035_news_newsheading1'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='playername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.players'),
        ),
    ]
