# Generated by Django 4.0.4 on 2022-06-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0036_teams_playername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='teamname',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='playername',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='newsheading1',
        ),
        migrations.AddField(
            model_name='news',
            name='newsheading',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Newsheading',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
