# Generated by Django 4.0.3 on 2022-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0038_player_teams_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teams',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Team'),
        ),
    ]
