# Generated by Django 4.0.3 on 2022-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0039_alter_teams_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Country'),
        ),
    ]
