# Generated by Django 4.0.3 on 2022-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0040_alter_player_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Team'),
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
