# Generated by Django 4.0.3 on 2022-06-21 16:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0041_remove_player_team_player_teams_delete_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='news'),
        ),
    ]
