# Generated by Django 4.0.3 on 2022-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0042_alter_news_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(default='', null=True, verbose_name='news'),
        ),
    ]
