# Generated by Django 4.0.3 on 2022-06-21 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0043_alter_news_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='news'),
        ),
    ]
