# Generated by Django 4.0.3 on 2022-06-21 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0044_alter_news_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=300, null=True, verbose_name='CName')),
                ('box', models.TextField(default='', null=True, verbose_name='Box')),
                ('cmted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teams.news')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
