# Generated by Django 4.0.3 on 2022-06-22 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0045_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsheading',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='newsheading'),
        ),
    ]
