# Generated by Django 4.0.3 on 2022-06-22 19:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0047_news_summary_news_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='teams',
            new_name='Teams',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cen',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hcen',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='para',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wick',
        ),
        migrations.AddField(
            model_name='player',
            name='Batting_style',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Batting_style'),
        ),
        migrations.AddField(
            model_name='player',
            name='Birthday',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='player',
            name='Bowling_style',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Bowling_style'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_100',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_100'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_10W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_10W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_50',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_50'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_5W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_5W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_Matches',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_Matches'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_Runs',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_Runs'),
        ),
        migrations.AddField(
            model_name='player',
            name='Ipl_Wickets',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Ipl_Wickets'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_100',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_100'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_10W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_10W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_50',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_50'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_5W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_5W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_Matches',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_Matches'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_Runs',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_Runs'),
        ),
        migrations.AddField(
            model_name='player',
            name='Odi_Wickets',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Odi_Wickets'),
        ),
        migrations.AddField(
            model_name='player',
            name='Para',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Para'),
        ),
        migrations.AddField(
            model_name='player',
            name='Role',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_100',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_100'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_10W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_10W'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_50',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_50'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_5W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_5W'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_Matches',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_Matches'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_Runs',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_Runs'),
        ),
        migrations.AddField(
            model_name='player',
            name='T20_Wickets',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='T20_Wickets'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_100',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_100'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_10W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_10W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_50',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_50'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_5W',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_5W'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_Matches',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_Matches'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_Runs',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_Runs'),
        ),
        migrations.AddField(
            model_name='player',
            name='Test_Wickets',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Test_Wickets'),
        ),
    ]
