# Generated by Django 4.0.4 on 2022-06-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0049_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Model_pic',
            field=models.ImageField(default='', null=True, upload_to='chicks/', verbose_name='Model_pic'),
        ),
    ]
